[params]
  # color style
  color = 'wheat'                           # linen, wheat, gray, light

  # header social icons
  github = 'angelajt'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'angelajt'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = ''                 # gravatar email or image url
  name = 'Angela'
  bio = """
  loves: reading, birdwatching, and hiking. 
  
  dislikes: writing bios.
  """


  # misc
  # disableHLJS = true                        # disable highlight.js
  # disablePostNavigation = true              # disable post navigation
  # monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # math = true                               # enable KaTeX math typesetting globally
  # localKatex = false                        # use local KaTeX js/css instead of CDN
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  # favicon = "favicon.ico"                   # customize the default favicon
  # appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon
